AWSTemplateFormatVersion: 2010-09-09
Description: 'Master stack: PathToMasterStackFile'

Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      BucketName: dev-bucket